(deftheme bloodbrew
  "Lobotomy Corporation and Bloodborne inspired theme.")

(custom-theme-set-faces
 'bloodbrew
 '(default ((t (:background "firebrick4" :foreground "tomato"))))
 '(org-hide ((t (:foreground "firebrick4"))))
 '(fringe ((t (:background "firebrick4"))))
 '(font-lock-builtin-face ((t (:foreground "PaleVioletRed"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "plum"))))
 '(font-lock-negation-char-face ((t (:foreground "lavender"))))
 '(font-lock-preprocessor-face ((t (:foreground "PaleTurquoise3"))))
 '(font-lock-string-face ((t (:foreground "SeaGreen"))))
 '(font-lock-variable-name-face ((t (:foreground "yellow3"))))
 '(font-lock-warning-face ((t (:foreground "MediumOrchid1"))))
 '(font-lock-comment-face ((t (:foreground "plum"))))
 '(font-lock-doc-face ((t (:foreground "MistyRose"))))
 '(font-lock-doc-markup-face ((t (:foreground "SeaGreen3"))))
 '(font-lock-function-name-face ((t (:foreground "MediumPurple"))))
 '(font-lock-keyword-face ((t (:foreground "SandyBrown"))))
 '(font-lock-type-face ((t (:foreground "BlanchedAlmond"))))
 '(rainbow-delimiters-depth-5-face ((t (:foreground "DarkGoldenrod"))))
 '(rainbow-delimiters-depth-4-face ((t (:foreground "goldenrod"))))
 '(rainbow-delimiters-depth-3-face ((t (:foreground "LightGoldenrod"))))
 '(rainbow-delimiters-depth-2-face ((t (:foreground "PaleGoldenrod"))))
 '(rainbow-delimiters-depth-1-face ((t (:foreground "cornsilk"))))
 '(rainbow-delimiters-depth-6-face ((t (:foreground "PowderBlue"))))
 '(rainbow-delimiters-depth-7-face ((t (:foreground "CadetBlue"))))
 '(rainbow-delimiters-depth-8-face ((t (:foreground "DodgerBlue"))))
 '(rainbow-delimiters-depth-9-face ((t (:foreground "SlateBlue"))))
 '(rainbow-delimiters-unmatched-face ((t (:foreground "DimGrey"))))
 '(mode-line-active ((t (:background "black" :foreground "PaleVioletRed"))))
 '(mode-line-inactive ((t (:background "black" :foreground "PaleVioletRed4"))))
 '(region ((t (:background "PeachPuff"))))
 )

(provide-theme 'bloodbrew)
